services:
  database:
    ports:
      - "5432:5432"

  api:
    command: npm run start:dev
    volumes:
      - ./api:/app
      - /app/node_modules

  app:
    command: npm run web
    volumes:
      - ./application:/app
      - /app/node_modules